---
title: "First Knit"
author: "Sophia Castellon"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
 
 I attended high school at Pete Knight High School and then I went to R Rex Parris. I graduated at R Rex Parris recently. I thought my math class was always easier for me. I think I did the best in art and italian class.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 
 I have a windows computer, I would say I'm pretty good with computers for just the basics so I would say I am about a 5. My internet connection is typically pretty good.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     

 Most people call me Soph as it is shorter and easier, but either Sophia or Soph is great! 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
 
  I want to be able to give my parents back what they gave me. I think I will probably be the best in the art or language class I am going to have to take as those were always something I liked to do. I am trying to become a registered nurse 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     

 I have been to two different countries! I have been to Japan and El Salvador. I have not been in the military and I have not been drafted and hopefully I will never have to do that I don't think I would be strong enough.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
 
 I am taking math 115 for the purpose of education requirements, I am not super sure what grade I will need in this class as I haven't been able to talk to a counsulor but I am assuming it would have to be somewhere between an A to C  
   
 






  




